baseURL = "https://hussyvel.com/"
theme = "PaperMod"
defaultContentLanguage = "en"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hussyvel"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/hussyvelribeiro"

[languages]
  # ==========================================
  # IDIOMA 1: INGLÊS (Padrão)
  # ==========================================
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Hussyvel Ribeiro | Tech Blog"

    [languages.en.params.profileMode]
      enabled = true
      title = "Hi, I'm Hussyvel 👋"
      subtitle = "Full Stack Software Developer | Java, GO, C, Javascript (Angular) and SQL"
      imageUrl = "/img/perfil-linkedin2.jpeg"
      imageWidth = 150
      imageHeight = 150

[[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 10

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 20

    [[languages.en.menu.main]]
      identifier = "java"
      name = "Java"
      url = "/java/"
      weight = 30

    [[languages.en.menu.main]]
      identifier = "javascript"
      name = "Javascript"
      url = "/javascript/"
      weight = 40

    [[languages.en.menu.main]]
      identifier = "c-lang"
      name = "C"
      url = "/c/"
      weight = 50

    [[languages.en.menu.main]]
      identifier = "go"
      name = "GO"
      url = "/go/"
      weight = 60

    [[languages.en.menu.main]]
      identifier = "sql"
      name = "SQL"
      url = "/sql/"
      weight = 70

    [[languages.en.menu.main]]
      identifier = "git"
      name = "Git"
      url = "/git/"
      weight = 80

    [[languages.en.menu.main]]
      identifier = "linux"
      name = "Linux"
      url = "/linux/"
      weight = 90

    [[languages.en.menu.main]]
      identifier = "redes"
      name = "Networking" # Em inglês fica melhor "Networking", mas a pasta pode ser /redes/
      url = "/redes/"
      weight = 100

    [[languages.en.menu.main]]
      identifier = "hardware"
      name = "Hardware"
      url = "/hardware/"
      weight = 110

    [[languages.pt.menu.main]]
      identifier = "AWS"
      name = "AWS"
      url = "/aws/"
      weight = 120

    [[languages.pt.menu.main]]
      identifier = "Services"
      name = "Services"
      url = "/services/"
      weight = 130

    [[languages.en.menu.main]]
      identifier = "resume"
      name = "Resume" # Na área de tecnologia em inglês, "Resume" é mais usado que "Curriculum"
      url = "/resume/"
      weight = 140
    
    

  # ==========================================
  # IDIOMA 2: PORTUGUÊS
  # ==========================================
  [languages.pt]
    languageName = "Português"
    weight = 2
    title = "Hussyvel Ribeiro | Blog de Tecnologia"

    [languages.pt.params.profileMode]
      enabled = true
      title = "Olá, sou o Hussyvel 👋"
      subtitle = "Desenvolvedor de Software Full Stack | Java, GO, C, Javascript (Angular) e SQL"
      imageUrl = "/img/perfil-linkedin2.jpeg"
      imageWidth = 150
      imageHeight = 150

[[languages.pt.menu.main]]
      identifier = "posts"
      name = "Artigos"
      url = "/pt/posts/"
      weight = 10

    [[languages.pt.menu.main]]
      identifier = "about"
      name = "Sobre Mim"
      url = "/pt/about/"
      weight = 20

    [[languages.pt.menu.main]]
      identifier = "java"
      name = "Java"
      url = "/pt/java/"
      weight = 30

    [[languages.pt.menu.main]]
      identifier = "javascript"
      name = "Javascript"
      url = "/pt/javascript/"
      weight = 40

    [[languages.pt.menu.main]]
      identifier = "c-lang"
      name = "C"
      url = "/pt/c/"
      weight = 50

    [[languages.pt.menu.main]]
      identifier = "go"
      name = "GO"
      url = "/pt/go/"
      weight = 60

    [[languages.pt.menu.main]]
      identifier = "sql"
      name = "SQL"
      url = "/pt/sql/"
      weight = 70

    [[languages.pt.menu.main]]
      identifier = "git"
      name = "Git"
      url = "/pt/git/"
      weight = 80

    [[languages.pt.menu.main]]
      identifier = "linux"
      name = "Linux"
      url = "/pt/linux/"
      weight = 90

    [[languages.pt.menu.main]]
      identifier = "redes"
      name = "Redes"
      url = "/pt/redes/"
      weight = 100

    [[languages.pt.menu.main]]
      identifier = "hardware"
      name = "Hardware"
      url = "/pt/hardware/"
      weight = 110

     [[languages.pt.menu.main]]
      identifier = "AWS"
      name = "AWS"
      url = "/pt/aws/"
      weight = 120

      [[languages.pt.menu.main]]
      identifier = "services"
      name = "Serviços"
      url = "/pt/services/"
      weight = 130

    [[languages.pt.menu.main]]
      identifier = "resume"
      name = "Currículo"
      url = "/pt/resume/"
      weight = 140